// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_ACTIVE  Status = 0
	Status_DONE    Status = 1
	Status_DELETED Status = 2
)

var Status_name = map[int32]string{
	0: "ACTIVE",
	1: "DONE",
	2: "DELETED",
}
var Status_value = map[string]int32{
	"ACTIVE":  0,
	"DONE":    1,
	"DELETED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_todo_2d9a008363c9cf02, []int{0}
}

type Item struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_2d9a008363c9cf02, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ACTIVE
}

type ListRequest struct {
	ShowInactive         bool     `protobuf:"varint,1,opt,name=showInactive,proto3" json:"showInactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_2d9a008363c9cf02, []int{1}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetShowInactive() bool {
	if m != nil {
		return m.ShowInactive
	}
	return false
}

type ListReply struct {
	Items                []Status `protobuf:"varint,1,rep,packed,name=items,proto3,enum=Status" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_2d9a008363c9cf02, []int{2}
}
func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (dst *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(dst, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetItems() []Status {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_2d9a008363c9cf02, []int{3}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_2d9a008363c9cf02, []int{4}
}
func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (dst *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(dst, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListReply)(nil), "ListReply")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "CreateReply")
	proto.RegisterEnum("Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToDoClient is the client API for ToDo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToDoClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
}

type toDoClient struct {
	cc *grpc.ClientConn
}

func NewToDoClient(cc *grpc.ClientConn) ToDoClient {
	return &toDoClient{cc}
}

func (c *toDoClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/ToDo/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/ToDo/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToDoServer is the server API for ToDo service.
type ToDoServer interface {
	List(context.Context, *ListRequest) (*ListReply, error)
	Create(context.Context, *CreateRequest) (*CreateReply, error)
}

func RegisterToDoServer(s *grpc.Server, srv ToDoServer) {
	s.RegisterService(&_ToDo_serviceDesc, srv)
}

func _ToDo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ToDo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ToDo/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ToDo",
	HandlerType: (*ToDoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ToDo_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ToDo_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_todo_2d9a008363c9cf02) }

var fileDescriptor_todo_2d9a008363c9cf02 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x93, 0x1a, 0x93, 0xf6, 0x25, 0x96, 0x30, 0xa7, 0x50, 0x10, 0xc3, 0x7a, 0x30, 0x54,
	0x58, 0xb0, 0x1e, 0x3d, 0x49, 0x93, 0x43, 0xa0, 0x28, 0xc4, 0xe0, 0x3d, 0xea, 0xa2, 0x01, 0xd3,
	0xad, 0xdd, 0xa9, 0xe2, 0xbf, 0x97, 0x26, 0x46, 0x52, 0xf0, 0xb6, 0xf3, 0x98, 0xfd, 0xf6, 0x7b,
	0x0b, 0xb0, 0x7e, 0xd1, 0x72, 0xb3, 0xd5, 0xac, 0xc5, 0x0d, 0x9c, 0x9c, 0x55, 0x43, 0x04, 0x67,
	0x5d, 0x35, 0x2a, 0xb2, 0x63, 0x3b, 0x99, 0x14, 0xed, 0x99, 0xce, 0xe0, 0x1a, 0xae, 0x78, 0x67,
	0xa2, 0x51, 0x6c, 0x27, 0xd3, 0x85, 0x27, 0x1f, 0xda, 0xb1, 0xf8, 0x8d, 0xc5, 0x15, 0xfc, 0x55,
	0x6d, 0xb8, 0x50, 0x1f, 0x3b, 0x65, 0x98, 0x04, 0x02, 0xf3, 0xa6, 0xbf, 0xf2, 0x75, 0xf5, 0xcc,
	0xf5, 0x67, 0xc7, 0x1a, 0x17, 0x07, 0x99, 0x98, 0x63, 0xd2, 0x5d, 0xd9, 0xbc, 0x7f, 0xd3, 0x29,
	0x8e, 0x6b, 0x56, 0x8d, 0x89, 0xec, 0xf8, 0x68, 0xc8, 0xef, 0x52, 0x71, 0x8e, 0x93, 0xe5, 0x56,
	0x55, 0xac, 0xfa, 0x07, 0xfe, 0x91, 0x14, 0x17, 0xf0, 0xfb, 0xa5, 0x3d, 0x32, 0x82, 0xd7, 0x28,
	0x63, 0xaa, 0xd7, 0x7e, 0xab, 0x1f, 0xe7, 0x97, 0x70, 0x3b, 0x3c, 0x01, 0xee, 0xed, 0xb2, 0xcc,
	0x1f, 0xb3, 0xd0, 0xa2, 0x31, 0x9c, 0xf4, 0xfe, 0x2e, 0x0b, 0x6d, 0xf2, 0xe1, 0xa5, 0xd9, 0x2a,
	0x2b, 0xb3, 0x34, 0x1c, 0x2d, 0x4a, 0x38, 0xa5, 0x4e, 0x35, 0x09, 0x38, 0x7b, 0x5d, 0x0a, 0xe4,
	0xa0, 0xe8, 0x0c, 0xf2, 0xaf, 0x83, 0xb0, 0x28, 0x81, 0xdb, 0x19, 0xd0, 0x54, 0x1e, 0xf8, 0xce,
	0x02, 0x39, 0x50, 0x13, 0xd6, 0x93, 0xdb, 0xfe, 0xf9, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xfc, 0x1b, 0xbc, 0xd0, 0x81, 0x01, 0x00, 0x00,
}
