// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemStatus int32

const (
	ItemStatus_ACTIVE  ItemStatus = 0
	ItemStatus_DONE    ItemStatus = 1
	ItemStatus_DELETED ItemStatus = 2
)

var ItemStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "DONE",
	2: "DELETED",
}
var ItemStatus_value = map[string]int32{
	"ACTIVE":  0,
	"DONE":    1,
	"DELETED": 2,
}

func (x ItemStatus) String() string {
	return proto.EnumName(ItemStatus_name, int32(x))
}
func (ItemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_todo_f4979e2759c3fcba, []int{0}
}

type Item struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               ItemStatus `protobuf:"varint,2,opt,name=status,proto3,enum=todo.ItemStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_f4979e2759c3fcba, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetStatus() ItemStatus {
	if m != nil {
		return m.Status
	}
	return ItemStatus_ACTIVE
}

type ListRequest struct {
	ShowInactive         bool     `protobuf:"varint,1,opt,name=showInactive,proto3" json:"showInactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_f4979e2759c3fcba, []int{1}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetShowInactive() bool {
	if m != nil {
		return m.ShowInactive
	}
	return false
}

type ListReply struct {
	Items                []ItemStatus `protobuf:"varint,1,rep,packed,name=items,proto3,enum=todo.ItemStatus" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_f4979e2759c3fcba, []int{2}
}
func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (dst *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(dst, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetItems() []ItemStatus {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_f4979e2759c3fcba, []int{3}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_f4979e2759c3fcba, []int{4}
}
func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (dst *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(dst, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "todo.Item")
	proto.RegisterType((*ListRequest)(nil), "todo.ListRequest")
	proto.RegisterType((*ListReply)(nil), "todo.ListReply")
	proto.RegisterType((*CreateRequest)(nil), "todo.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "todo.CreateReply")
	proto.RegisterEnum("todo.ItemStatus", ItemStatus_name, ItemStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/todo.Api/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/todo.Api/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	List(context.Context, *ListRequest) (*ListReply, error)
	Create(context.Context, *CreateRequest) (*CreateReply, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Api/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Api/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Api_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Api_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_todo_f4979e2759c3fcba) }

var fileDescriptor_todo_f4979e2759c3fcba = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0xda, 0x98, 0xb6, 0x2f, 0x7e, 0xa4, 0xe3, 0x25, 0xf4, 0x14, 0x56, 0xd0, 0x20, 0x52,
	0x31, 0xfd, 0x05, 0xa5, 0xc9, 0x21, 0x50, 0x14, 0x62, 0xf1, 0x1e, 0x75, 0xa9, 0x81, 0xa6, 0x89,
	0xdd, 0xa9, 0xd2, 0x7f, 0x2f, 0xc9, 0x1a, 0xda, 0x40, 0x6f, 0xb3, 0xef, 0x63, 0xde, 0x1b, 0x16,
	0xe0, 0xe2, 0xb3, 0x98, 0x94, 0xdb, 0x82, 0x0b, 0x32, 0xab, 0x59, 0x84, 0x30, 0x63, 0x96, 0x39,
	0x11, 0xcc, 0x4d, 0x9a, 0x4b, 0xd7, 0xf0, 0x0c, 0x7f, 0x98, 0xd4, 0x33, 0xf9, 0xb0, 0x14, 0xa7,
	0xbc, 0x53, 0x6e, 0xd7, 0x33, 0xfc, 0xcb, 0xc0, 0x99, 0xd4, 0xf6, 0x4a, 0xff, 0x5a, 0xe3, 0xc9,
	0x3f, 0x2f, 0x9e, 0x60, 0x2f, 0x32, 0xc5, 0x89, 0xfc, 0xde, 0x49, 0xc5, 0x24, 0x70, 0xae, 0xbe,
	0x8a, 0xdf, 0x78, 0x93, 0x7e, 0x70, 0xf6, 0xa3, 0x97, 0x0e, 0x92, 0x16, 0x26, 0xa6, 0x18, 0x6a,
	0x4b, 0xb9, 0xde, 0xd3, 0x2d, 0xce, 0x32, 0x96, 0xb9, 0x72, 0x0d, 0xaf, 0x77, 0x32, 0x48, 0xd3,
	0xe2, 0x06, 0x17, 0xf3, 0xad, 0x4c, 0x59, 0x36, 0x49, 0x27, 0x6a, 0x8b, 0x3b, 0xd8, 0x8d, 0xa8,
	0xda, 0xed, 0xa2, 0x9f, 0x4b, 0xa5, 0xd2, 0x55, 0xa3, 0x6a, 0x9e, 0xf7, 0x8f, 0xc0, 0x21, 0x82,
	0x00, 0x6b, 0x36, 0x5f, 0xc6, 0x6f, 0x91, 0xd3, 0xa1, 0x01, 0xcc, 0xf0, 0xe5, 0x39, 0x72, 0x0c,
	0xb2, 0xd1, 0x0f, 0xa3, 0x45, 0xb4, 0x8c, 0x42, 0xa7, 0x1b, 0xac, 0xd0, 0x9b, 0x95, 0x19, 0x3d,
	0xc0, 0xac, 0xaa, 0xd3, 0x48, 0xd7, 0x3c, 0xba, 0x7c, 0x7c, 0x75, 0x0c, 0x95, 0xeb, 0xbd, 0xe8,
	0x50, 0x00, 0x4b, 0xd7, 0xa1, 0x6b, 0x4d, 0xb6, 0x2e, 0x18, 0x8f, 0xda, 0x60, 0xed, 0x79, 0xb7,
	0xea, 0x2f, 0x9a, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xb3, 0x6a, 0x67, 0xb0, 0x01, 0x00,
	0x00,
}
