// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: todo.proto

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	Item
	ListRequest
	ListReply
	CreateRequest
	CreateReply
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Api service

type ApiService interface {
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListReply, error)
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateReply, error)
}

type apiService struct {
	c    client.Client
	name string
}

func NewApiService(name string, c client.Client) ApiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "todo"
	}
	return &apiService{
		c:    c,
		name: name,
	}
}

func (c *apiService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListReply, error) {
	req := c.c.NewRequest(c.name, "Api.List", in)
	out := new(ListReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateReply, error) {
	req := c.c.NewRequest(c.name, "Api.Create", in)
	out := new(CreateReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiHandler interface {
	List(context.Context, *ListRequest, *ListReply) error
	Create(context.Context, *CreateRequest, *CreateReply) error
}

func RegisterApiHandler(s server.Server, hdlr ApiHandler, opts ...server.HandlerOption) {
	type api interface {
		List(ctx context.Context, in *ListRequest, out *ListReply) error
		Create(ctx context.Context, in *CreateRequest, out *CreateReply) error
	}
	type Api struct {
		api
	}
	h := &apiHandler{hdlr}
	s.Handle(s.NewHandler(&Api{h}, opts...))
}

type apiHandler struct {
	ApiHandler
}

func (h *apiHandler) List(ctx context.Context, in *ListRequest, out *ListReply) error {
	return h.ApiHandler.List(ctx, in, out)
}

func (h *apiHandler) Create(ctx context.Context, in *CreateRequest, out *CreateReply) error {
	return h.ApiHandler.Create(ctx, in, out)
}
