// Code generated by protoc-gen-go. DO NOT EDIT.
// source: projects.proto

package projects

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemStatus int32

const (
	ItemStatus_ACTIVE  ItemStatus = 0
	ItemStatus_DONE    ItemStatus = 1
	ItemStatus_DELETED ItemStatus = 2
)

var ItemStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "DONE",
	2: "DELETED",
}
var ItemStatus_value = map[string]int32{
	"ACTIVE":  0,
	"DONE":    1,
	"DELETED": 2,
}

func (x ItemStatus) String() string {
	return proto.EnumName(ItemStatus_name, int32(x))
}
func (ItemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_projects_35d795cddb22f109, []int{0}
}

type Item struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               ItemStatus `protobuf:"varint,2,opt,name=status,proto3,enum=projects.ItemStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_projects_35d795cddb22f109, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetStatus() ItemStatus {
	if m != nil {
		return m.Status
	}
	return ItemStatus_ACTIVE
}

type ListRequest struct {
	ShowInactive         bool     `protobuf:"varint,1,opt,name=showInactive,proto3" json:"showInactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_projects_35d795cddb22f109, []int{1}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetShowInactive() bool {
	if m != nil {
		return m.ShowInactive
	}
	return false
}

type ListReply struct {
	Items                []ItemStatus `protobuf:"varint,1,rep,packed,name=items,proto3,enum=projects.ItemStatus" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_projects_35d795cddb22f109, []int{2}
}
func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (dst *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(dst, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetItems() []ItemStatus {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_projects_35d795cddb22f109, []int{3}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_projects_35d795cddb22f109, []int{4}
}
func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (dst *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(dst, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "projects.Item")
	proto.RegisterType((*ListRequest)(nil), "projects.ListRequest")
	proto.RegisterType((*ListReply)(nil), "projects.ListReply")
	proto.RegisterType((*CreateRequest)(nil), "projects.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "projects.CreateReply")
	proto.RegisterEnum("projects.ItemStatus", ItemStatus_name, ItemStatus_value)
}

func init() { proto.RegisterFile("projects.proto", fileDescriptor_projects_35d795cddb22f109) }

var fileDescriptor_projects_35d795cddb22f109 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0x36, 0xa6, 0xe9, 0x8b, 0x96, 0x30, 0x5a, 0x0c, 0x3d, 0x85, 0xf5, 0x60, 0x29,
	0x52, 0xb1, 0x0a, 0x82, 0xb7, 0xd2, 0x04, 0x0c, 0x14, 0x85, 0x58, 0xbc, 0xc7, 0xb2, 0x68, 0xa4,
	0x69, 0x62, 0x76, 0x6b, 0xe9, 0xb7, 0x97, 0x24, 0xae, 0xb1, 0xfe, 0xb9, 0xed, 0xcc, 0xfc, 0xe6,
	0xbd, 0xb7, 0xbb, 0xe8, 0x66, 0x79, 0xfa, 0xca, 0x17, 0x52, 0x8c, 0xb2, 0x3c, 0x95, 0x29, 0x99,
	0xaa, 0x66, 0xb7, 0xd0, 0x03, 0xc9, 0x13, 0x22, 0xe8, 0xab, 0x28, 0xe1, 0x8e, 0xe6, 0x6a, 0x83,
	0x4e, 0x58, 0x9e, 0xe9, 0x0c, 0x86, 0x90, 0x91, 0x5c, 0x0b, 0xa7, 0xe9, 0x6a, 0x83, 0xee, 0xf8,
	0x68, 0xf4, 0x25, 0x53, 0xec, 0x3c, 0x94, 0xb3, 0xf0, 0x93, 0x61, 0x17, 0xb0, 0x66, 0xb1, 0x90,
	0x21, 0x7f, 0x5b, 0x73, 0x21, 0x89, 0x61, 0x5f, 0xbc, 0xa4, 0x9b, 0x60, 0x15, 0x2d, 0x64, 0xfc,
	0x5e, 0x09, 0x9b, 0xe1, 0x4e, 0x8f, 0x5d, 0xa3, 0x53, 0xad, 0x64, 0xcb, 0x2d, 0x0d, 0xb1, 0x17,
	0x4b, 0x9e, 0x08, 0x47, 0x73, 0x5b, 0xff, 0x9a, 0x55, 0x08, 0x3b, 0xc1, 0xc1, 0x34, 0xe7, 0x91,
	0xe4, 0xca, 0xed, 0x8f, 0xf8, 0xec, 0x14, 0x96, 0x82, 0x0a, 0x7d, 0x07, 0xed, 0x84, 0x0b, 0x11,
	0x3d, 0x2b, 0x4a, 0x95, 0xc3, 0x73, 0xa0, 0xb6, 0x20, 0xc0, 0x98, 0x4c, 0xe7, 0xc1, 0xa3, 0x6f,
	0x37, 0xc8, 0x84, 0xee, 0xdd, 0xdf, 0xf9, 0xb6, 0x46, 0x16, 0xda, 0x9e, 0x3f, 0xf3, 0xe7, 0xbe,
	0x67, 0x37, 0xc7, 0x1b, 0xb4, 0x26, 0x59, 0x4c, 0x57, 0xd0, 0x8b, 0xf8, 0xd4, 0xab, 0xa3, 0x7e,
	0x7b, 0x81, 0xfe, 0xe1, 0xcf, 0x76, 0xb6, 0xdc, 0xb2, 0x06, 0xdd, 0xc0, 0xa8, 0x62, 0xd1, 0x71,
	0x0d, 0xec, 0xdc, 0xa6, 0xdf, 0xfb, 0x3d, 0x28, 0x77, 0x9f, 0x8c, 0xf2, 0xfb, 0x2e, 0x3f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x7a, 0xbd, 0x5e, 0x49, 0xd0, 0x01, 0x00, 0x00,
}
