version: '2'

services:
    todo:
        build: .
        image: nizsheanez/todo:latest
        container_name: "nizsheanez"
        hostname: "localhost"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        # uncomment to expose directly (no proxy)
        ports:
          - "80:8080"

        environment:
            - SECRET="asd"
            - MONGO_URL=mongo:27018
            - DEBUG=true
            # - DEV_PASSWD=password # development mode, be careful!
